// Generated by Avo. You should never have to make changes to this file.
// If you find yourself in the situation where you have to edit the file please contact us at hi@avo.app.
// If you encounter a git conflict in this file run `avo pull` and it will be resolved automatically.
/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
import * as AvoRuntime from '../Avo';

import { EVENT_HASH__85XS456XE_3052dfca } from './EventHashes0';
import type { AvoAssertMessage } from '../Avo';

import type {
AuthenticationConfigValueType,
BranchPromptInteractionValueType,
BranchPromptTypeValueType,
SchemaBillingStatusValueType,
SchemaSubscriptionPlanSlugValueType,
SchemaSubscriptionPlanValueType,
SchemaTrialPlanSlugValueType,
SchemaTrialPlanValueType,
SchemaTypeValueType
} from '../Avo';
export interface BranchPromptInteractionProperties {
  schemaId: string;
  schemaName: string | null | undefined;
  schemaBillingStatus: SchemaBillingStatusValueType;
  branchId: string;
  branchName: string;
  schemaSubscriptionPlan: SchemaSubscriptionPlanValueType;
  schemaTrialPlan: SchemaTrialPlanValueType | null | undefined;
  authenticationConfig: AuthenticationConfigValueType;
  schemaSubscriptionPlanSlug: SchemaSubscriptionPlanSlugValueType;
  schemaTrialPlanSlug: SchemaTrialPlanSlugValueType | null | undefined;
  schemaType: SchemaTypeValueType;
  branchPromptInteraction: BranchPromptInteractionValueType;
  branchPromptType: BranchPromptTypeValueType;
  associateEventWithBranch: string;
  associateEventWithWorkspace: string;
}
/**
 * Branch Prompt Interaction: Event sent when a user interacts with the branch prompt popup when they either try to edit main, pull an item to main or edit a branch that has already been marked as ready for review
 * 
 * @param properties the properties associated with this event
 * @param properties.schemaId: The ID of the schema that this event is related to.
 * @param properties.schemaName: Name of the schema that this event is related to.
 * @param properties.schemaBillingStatus: The status of the payment plan this schema is on, when (before) this event is triggered. Note that the 'Team' property value basically covers any paid plan. The 'Team' property value could effectively be 'Paying'.
 * @param properties.branchId: The ID of the branch that this event is related to.
 * @param properties.branchName: The name of the branch that this event is related to.
 * @param properties.schemaSubscriptionPlan: Current workspace subscription plan
 * @param properties.schemaTrialPlan: The plan that is currently being trialed
 * @param properties.authenticationConfig: Configured authentication method for workspace
 * @param properties.schemaSubscriptionPlanSlug: The slug (as seen in retool) of the subscription plan that the schema is on when the event is sent
 * @param properties.schemaTrialPlanSlug: The slug (as seen in retool) of the subscription plan that the schema is currently trialing – when the event is sent
 * @param properties.schemaType: Describes whether the workspace is a regular workspace or a sandbox workspace
 * @param properties.branchPromptInteraction: How the user interacted with the branch prompt
 * @param properties.branchPromptType: Whether the branch prompt was displayed because of a user trying to edit on main or pull into main
 * @param properties.associateEventWithBranch (id of the Branch group to associate current log event call with): no description
 * @param properties.associateEventWithWorkspace (id of the Workspace group to associate current log event call with): no description
 * 
 * @see {@link https://www.avo.app/schemas/fwtXqAc0fCLy7b7oGW40/events/85XS456XE}
 */
export function branchPromptInteraction(properties: BranchPromptInteractionProperties) {
  
  // Get destinations from AvoRuntime
  const { 
    AvoEnv,
    __AVO_ENV__,
    __AVO_NOOP__,
    __AVO_LOGGER__,
    __STRICT__,
    __REPORT_FAILURE_AS__,
    InternalAvoLogger,
    array_difference,
    AvoAssert,
    _avo_invoke,
    _avo_invoke_meta,
    convertPropertiesArrayToMap,
    getSystemProperties,
    __WEB_DEBUGGER__,
    _avo_debugger_log,
    __INSPECTOR__,
    SegmentInspectorForDocs,
    Intercom,
    Fullstory,
    Mixpanel } = AvoRuntime;
  // Get system properties at runtime when the function is called
  const {
    sysClient,
    sysVersion
  } = getSystemProperties();
  
  // @ts-ignore
  let eventPropertiesArray: array = [];
  eventPropertiesArray.push({id: "40958e87-d69a-4d5a-98f8-b36922466787", name: "Schema Id", value: properties.schemaId});
  properties.schemaName !== undefined && properties.schemaName !== null ?
    eventPropertiesArray.push({id: "a49af1dc-3166-45db-a906-86179135854b", name: "Schema Name", value: properties.schemaName}) :
    eventPropertiesArray.push({id: "a49af1dc-3166-45db-a906-86179135854b", name: "Schema Name", value: null});
  eventPropertiesArray.push({id: "bf9e6b00-ce68-4379-9172-134a5ab4d495", name: "Schema Billing Status", value: properties.schemaBillingStatus});
  eventPropertiesArray.push({id: "tlrUtYcti", name: "Branch Id", value: properties.branchId});
  eventPropertiesArray.push({id: "9xcXzuN-3", name: "Branch Name", value: properties.branchName});
  eventPropertiesArray.push({id: "KZ9nbzWseP", name: "Schema Subscription Plan", value: properties.schemaSubscriptionPlan});
  properties.schemaTrialPlan !== undefined && properties.schemaTrialPlan !== null ?
    eventPropertiesArray.push({id: "hoYGdti-jm", name: "Schema Trial Plan", value: properties.schemaTrialPlan}) :
    eventPropertiesArray.push({id: "hoYGdti-jm", name: "Schema Trial Plan", value: null});
  eventPropertiesArray.push({id: "FlvR9BrYsX", name: "Authentication Config", value: properties.authenticationConfig});
  eventPropertiesArray.push({id: "VbCcDZsBB", name: "Schema Subscription Plan Slug", value: properties.schemaSubscriptionPlanSlug});
  properties.schemaTrialPlanSlug !== undefined && properties.schemaTrialPlanSlug !== null ?
    eventPropertiesArray.push({id: "wJEm0-Jtu3", name: "Schema Trial Plan Slug", value: properties.schemaTrialPlanSlug}) :
    eventPropertiesArray.push({id: "wJEm0-Jtu3", name: "Schema Trial Plan Slug", value: null});
  eventPropertiesArray.push({id: "BNJvykjYU", name: "Schema Type", value: properties.schemaType});
  eventPropertiesArray.push({id: "HC5owTREY", name: "Branch Prompt Interaction", value: properties.branchPromptInteraction});
  eventPropertiesArray.push({id: "ItiKtj7ouhnEfpNVFX6Gc", name: "Branch Prompt Type", value: properties.branchPromptType});
  eventPropertiesArray.push({id: "9e5c4ff5-d5f6-4e82-b061-d5fa02755aae", name: "Client", value: sysClient});
  eventPropertiesArray.push({id: "2fad5bf3-7782-49a2-acc2-825daf823095", name: "Version", value: sysVersion});
  let eventProperties = convertPropertiesArrayToMap(eventPropertiesArray)
  // @ts-ignore
  let userPropertiesArray: array = [];
  let userProperties = convertPropertiesArrayToMap(userPropertiesArray)
  // assert properties
  if (__AVO_ENV__ !== AvoEnv.Prod || __WEB_DEBUGGER__) {
    let messages: AvoAssertMessage[] = [];
    // debug console in Avo
    if (!__AVO_NOOP__) {
      _avo_invoke(__AVO_ENV__, "85XS456XE", EVENT_HASH__85XS456XE_3052dfca, messages.map(m => Object.assign({}, {tag: m.tag, propertyId: m.propertyId, additionalProperties: m.additionalProperties, actualType: m.actualType})), 'event');
    }
    InternalAvoLogger.logEventSent("Branch Prompt Interaction", eventProperties, userProperties);
    if (__WEB_DEBUGGER__) {
      // Avo web debugger
      _avo_debugger_log("85XS456XE", "Branch Prompt Interaction", messages, eventPropertiesArray, userPropertiesArray, [
      {id: "8d0839e1-443d-46b3-91c7-d7c84d5c8077event", groupName: "Branch", groupId: "8d0839e1-443d-46b3-91c7-d7c84d5c8077", name: "Associates event with group", value: properties.associateEventWithBranch},
      {id: "9f74af5b-39ac-4325-98db-a3eec66dc2caevent", groupName: "Workspace", groupId: "9f74af5b-39ac-4325-98db-a3eec66dc2ca", name: "Associates event with group", value: properties.associateEventWithWorkspace},
      ]);
    }
  }
  if (!__AVO_NOOP__) {
    if (__INSPECTOR__ != null) {
      // @ts-ignore
      __INSPECTOR__._avoFunctionTrackSchemaFromEvent("Branch Prompt Interaction", eventProperties, "85XS456XE", EVENT_HASH__85XS456XE_3052dfca);
    }
    // destination SegmentInspectorForDocs
    SegmentInspectorForDocs.logEvent("Branch Prompt Interaction", (Object as any).assign({}, eventProperties), {});
    
    // destination Intercom
    let intercomProperties = {};
    Intercom.logEvent("Branch Prompt Interaction", (Object as any).assign({}, intercomProperties));
    
    // destination Fullstory
    Fullstory.logEvent("Branch Prompt Interaction", (Object as any).assign({}, eventProperties));
    
    // destination Mixpanel
    Mixpanel.logEventWithGroups("Branch Prompt Interaction", (Object as any).assign({}, eventProperties), {
    "Branch": properties.associateEventWithBranch,
    "Workspace": properties.associateEventWithWorkspace,
    });
  } else {
    // do nothing
  }
}

export default branchPromptInteraction;