// Generated by Avo. You should never have to make changes to this file.
// If you find yourself in the situation where you have to edit the file please contact us at hi@avo.app.
// If you encounter a git conflict in this file run `avo pull` and it will be resolved automatically.
/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
import * as AvoRuntime from '../Avo';

import { EVENT_HASH__0FvnJgpVbz_795a0069 } from './EventHashes0';
import type { AvoAssertMessage } from '../Avo';

export interface ContentCopiedProperties {
  path: string;
  content: string | null | undefined;
}
/**
 * Content Copied: Called when a user copies text from the docs
 * 
 * @param properties the properties associated with this event
 * @param properties.path: pathname from the URL, e.g. 'https://www.avo.app/docs/quickstart/' -> 'docs/quickstart'
 * @param properties.content: no description
 * 
 * @see {@link https://www.avo.app/schemas/fwtXqAc0fCLy7b7oGW40/events/0FvnJgpVbz}
 */
export function contentCopied(properties: ContentCopiedProperties) {
  
  // Get destinations from AvoRuntime
  const { 
    AvoEnv,
    __AVO_ENV__,
    __AVO_NOOP__,
    __AVO_LOGGER__,
    __STRICT__,
    __REPORT_FAILURE_AS__,
    InternalAvoLogger,
    array_difference,
    AvoAssert,
    _avo_invoke,
    _avo_invoke_meta,
    convertPropertiesArrayToMap,
    getSystemProperties,
    __WEB_DEBUGGER__,
    _avo_debugger_log,
    __INSPECTOR__,
    SegmentInspectorForDocs,
    Intercom,
    Fullstory,
    Mixpanel } = AvoRuntime;
  // Get system properties at runtime when the function is called
  const {
    sysClient,
    sysVersion
  } = getSystemProperties();
  
  // @ts-ignore
  let eventPropertiesArray: array = [];
  eventPropertiesArray.push({id: "UT9ZlNsN2", name: "Path", value: properties.path});
  properties.content !== undefined && properties.content !== null ?
    eventPropertiesArray.push({id: "ktIiFeiz3N", name: "Content", value: properties.content}) :
    eventPropertiesArray.push({id: "ktIiFeiz3N", name: "Content", value: null});
  eventPropertiesArray.push({id: "9e5c4ff5-d5f6-4e82-b061-d5fa02755aae", name: "Client", value: sysClient});
  eventPropertiesArray.push({id: "2fad5bf3-7782-49a2-acc2-825daf823095", name: "Version", value: sysVersion});
  let eventProperties = convertPropertiesArrayToMap(eventPropertiesArray)
  // @ts-ignore
  let userPropertiesArray: array = [];
  let userProperties = convertPropertiesArrayToMap(userPropertiesArray)
  // assert properties
  if (__AVO_ENV__ !== AvoEnv.Prod || __WEB_DEBUGGER__) {
    let messages: AvoAssertMessage[] = [];
    // debug console in Avo
    if (!__AVO_NOOP__) {
      _avo_invoke(__AVO_ENV__, "0FvnJgpVbz", EVENT_HASH__0FvnJgpVbz_795a0069, messages.map(m => Object.assign({}, {tag: m.tag, propertyId: m.propertyId, additionalProperties: m.additionalProperties, actualType: m.actualType})), 'event');
    }
    InternalAvoLogger.logEventSent("Content Copied", eventProperties, userProperties);
    if (__WEB_DEBUGGER__) {
      // Avo web debugger
      _avo_debugger_log("0FvnJgpVbz", "Content Copied", messages, eventPropertiesArray, userPropertiesArray, []);
    }
  }
  if (!__AVO_NOOP__) {
    if (__INSPECTOR__ != null) {
      // @ts-ignore
      __INSPECTOR__._avoFunctionTrackSchemaFromEvent("Content Copied", eventProperties, "0FvnJgpVbz", EVENT_HASH__0FvnJgpVbz_795a0069);
    }
    // destination SegmentInspectorForDocs
    SegmentInspectorForDocs.logEvent("Content Copied", (Object as any).assign({}, eventProperties), {});
    
    // destination Intercom
    let intercomProperties = {};
    Intercom.logEvent("Content Copied", (Object as any).assign({}, intercomProperties));
    
    // destination Fullstory
    Fullstory.logEvent("Content Copied", (Object as any).assign({}, eventProperties));
    
    // destination Mixpanel
    Mixpanel.logEvent("Content Copied", (Object as any).assign({}, eventProperties));
  } else {
    // do nothing
  }
}

export default contentCopied;