// Generated by Avo. You should never have to make changes to this file.
// If you find yourself in the situation where you have to edit the file please contact us at hi@avo.app.
// If you encounter a git conflict in this file run `avo pull` and it will be resolved automatically.
/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
import * as AvoRuntime from '../Avo';

import { EVENT_HASH_J4cW6PmriY_42340bcd } from './EventHashes0';
import type { AvoAssertMessage } from '../Avo';

export interface DocsPageViewedProperties {
  utmSource: string | null | undefined;
  utmMedium: string | null | undefined;
  utmContent: string | null | undefined;
  utmCampaign: string | null | undefined;
  utmTerm: string | null | undefined;
  userId_: string;
  referrer: string | null | undefined;
  path: string;
}
/**
 * Docs Page Viewed: Sent when user opens one of the docs pages (which is not contained in our Landing Page Viewed event).
 * 
 * @param properties the properties associated with this event
 * @param properties.utmSource: Parsed from the link a user clicks to get to Avo.
 * @param properties.utmMedium: Parsed from the link a user clicks to get to Avo
 * @param properties.utmContent: Parsed from the link a user clicks to get to Avo
 * @param properties.utmCampaign: Identifies a specific product promotion or strategic campaign this event is part of
 * @param properties.utmTerm: Parsed from the link a user clicks to get to Avo.
 * @param properties.userId_: The value used to identify the user. Make sure it's a unique sequence of characters used to identify the user.
 * @param properties.referrer: First referrer seen for the user
 * @param properties.path: pathname from the URL, e.g. 'https://www.avo.app/docs/quickstart/' -> 'docs/quickstart'
 * 
 * @see {@link https://www.avo.app/schemas/fwtXqAc0fCLy7b7oGW40/events/J4cW6PmriY}
 */
export function docsPageViewed(properties: DocsPageViewedProperties) {
  
  // Get destinations from AvoRuntime
  const { 
    AvoEnv,
    __AVO_ENV__,
    __AVO_NOOP__,
    __AVO_LOGGER__,
    __STRICT__,
    __REPORT_FAILURE_AS__,
    InternalAvoLogger,
    array_difference,
    AvoAssert,
    _avo_invoke,
    _avo_invoke_meta,
    convertPropertiesArrayToMap,
    getSystemProperties,
    __WEB_DEBUGGER__,
    _avo_debugger_log,
    __INSPECTOR__,
    SegmentInspectorForDocs,
    Intercom,
    Fullstory,
    Mixpanel } = AvoRuntime;
  // Get system properties at runtime when the function is called
  const {
    sysClient,
    sysVersion
  } = getSystemProperties();
  
  // @ts-ignore
  let eventPropertiesArray: array = [];
  properties.utmSource !== undefined && properties.utmSource !== null ?
    eventPropertiesArray.push({id: "OLNULsfJZD", name: "UTM Source", value: properties.utmSource}) :
    eventPropertiesArray.push({id: "OLNULsfJZD", name: "UTM Source", value: null});
  properties.utmMedium !== undefined && properties.utmMedium !== null ?
    eventPropertiesArray.push({id: "wx_FcQt9oN", name: "UTM Medium", value: properties.utmMedium}) :
    eventPropertiesArray.push({id: "wx_FcQt9oN", name: "UTM Medium", value: null});
  properties.utmContent !== undefined && properties.utmContent !== null ?
    eventPropertiesArray.push({id: "-vBUKSLbCo", name: "UTM Content", value: properties.utmContent}) :
    eventPropertiesArray.push({id: "-vBUKSLbCo", name: "UTM Content", value: null});
  properties.utmCampaign !== undefined && properties.utmCampaign !== null ?
    eventPropertiesArray.push({id: "wbB7aeGs47", name: "UTM Campaign", value: properties.utmCampaign}) :
    eventPropertiesArray.push({id: "wbB7aeGs47", name: "UTM Campaign", value: null});
  properties.utmTerm !== undefined && properties.utmTerm !== null ?
    eventPropertiesArray.push({id: "Y0xLjpFlMc", name: "UTM Term", value: properties.utmTerm}) :
    eventPropertiesArray.push({id: "Y0xLjpFlMc", name: "UTM Term", value: null});
  eventPropertiesArray.push({id: "UT9ZlNsN2", name: "Path", value: properties.path});
  eventPropertiesArray.push({id: "9e5c4ff5-d5f6-4e82-b061-d5fa02755aae", name: "Client", value: sysClient});
  eventPropertiesArray.push({id: "2fad5bf3-7782-49a2-acc2-825daf823095", name: "Version", value: sysVersion});
  let eventProperties = convertPropertiesArrayToMap(eventPropertiesArray)
  // @ts-ignore
  let userPropertiesArray: array = [];
  let userProperties = convertPropertiesArrayToMap(userPropertiesArray)
  // assert properties
  if (__AVO_ENV__ !== AvoEnv.Prod || __WEB_DEBUGGER__) {
    let messages: AvoAssertMessage[] = [];
    // debug console in Avo
    if (!__AVO_NOOP__) {
      _avo_invoke(__AVO_ENV__, "J4cW6PmriY", EVENT_HASH_J4cW6PmriY_42340bcd, messages.map(m => Object.assign({}, {tag: m.tag, propertyId: m.propertyId, additionalProperties: m.additionalProperties, actualType: m.actualType})), 'event');
    }
    InternalAvoLogger.logEventSent("Docs Page Viewed", eventProperties, userProperties);
    if (__WEB_DEBUGGER__) {
      // Avo web debugger
      _avo_debugger_log("J4cW6PmriY", "Docs Page Viewed", messages, eventPropertiesArray, userPropertiesArray, []);
    }
  }
  if (!__AVO_NOOP__) {
    if (__INSPECTOR__ != null) {
      // @ts-ignore
      __INSPECTOR__._avoFunctionTrackSchemaFromEvent("Docs Page Viewed", eventProperties, "J4cW6PmriY", EVENT_HASH_J4cW6PmriY_42340bcd);
    }
    // destination SegmentInspectorForDocs
    SegmentInspectorForDocs.logEvent("Docs Page Viewed", (Object as any).assign({}, eventProperties), {});
    
    // destination Intercom
    let intercomProperties = {};
    Intercom.logEvent("Docs Page Viewed", (Object as any).assign({}, intercomProperties));
    
    // destination Fullstory
    Fullstory.logEvent("Docs Page Viewed", (Object as any).assign({}, eventProperties));
    
    // destination Mixpanel
    Mixpanel.logEvent("Docs Page Viewed", (Object as any).assign({}, eventProperties));
  } else {
    // do nothing
  }
}

export default docsPageViewed;