// Generated by Avo. You should never have to make changes to this file.
// If you find yourself in the situation where you have to edit the file please contact us at hi@avo.app.
// If you encounter a git conflict in this file run `avo pull` and it will be resolved automatically.
/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
import * as AvoRuntime from '../Avo';

import { EVENT_HASH_Pjs0MGxPME_58210381 } from './EventHashes0';
import type { AvoAssertMessage } from '../Avo';

export interface DocsPageErroredProperties {
  path: string;
  errorCode: string;
}
/**
 * Docs Page Errored: Sent when a docs page fails
 * 
 * @param properties the properties associated with this event
 * @param properties.path: pathname from the URL, e.g. 'https://www.avo.app/docs/quickstart/' -> 'docs/quickstart'
 * @param properties.errorCode: The HTTP error code
 * 
 * @see {@link https://www.avo.app/schemas/fwtXqAc0fCLy7b7oGW40/events/Pjs0MGxPME}
 */
export function docsPageErrored(properties: DocsPageErroredProperties) {
  
  // Get destinations from AvoRuntime
  const { 
    AvoEnv,
    __AVO_ENV__,
    __AVO_NOOP__,
    __AVO_LOGGER__,
    __STRICT__,
    __REPORT_FAILURE_AS__,
    InternalAvoLogger,
    array_difference,
    AvoAssert,
    _avo_invoke,
    _avo_invoke_meta,
    convertPropertiesArrayToMap,
    getSystemProperties,
    __WEB_DEBUGGER__,
    _avo_debugger_log,
    __INSPECTOR__,
    SegmentInspectorForDocs,
    Intercom,
    Fullstory,
    Mixpanel } = AvoRuntime;
  // Get system properties at runtime when the function is called
  const {
    sysClient,
    sysVersion
  } = getSystemProperties();
  
  // @ts-ignore
  let eventPropertiesArray: array = [];
  eventPropertiesArray.push({id: "UT9ZlNsN2", name: "Path", value: properties.path});
  eventPropertiesArray.push({id: "xlB65Vu0P", name: "Error Code", value: properties.errorCode});
  eventPropertiesArray.push({id: "9e5c4ff5-d5f6-4e82-b061-d5fa02755aae", name: "Client", value: sysClient});
  eventPropertiesArray.push({id: "2fad5bf3-7782-49a2-acc2-825daf823095", name: "Version", value: sysVersion});
  let eventProperties = convertPropertiesArrayToMap(eventPropertiesArray)
  // @ts-ignore
  let userPropertiesArray: array = [];
  let userProperties = convertPropertiesArrayToMap(userPropertiesArray)
  // assert properties
  if (__AVO_ENV__ !== AvoEnv.Prod || __WEB_DEBUGGER__) {
    let messages: AvoAssertMessage[] = [];
    // debug console in Avo
    if (!__AVO_NOOP__) {
      _avo_invoke(__AVO_ENV__, "Pjs0MGxPME", EVENT_HASH_Pjs0MGxPME_58210381, messages.map(m => Object.assign({}, {tag: m.tag, propertyId: m.propertyId, additionalProperties: m.additionalProperties, actualType: m.actualType})), 'event');
    }
    InternalAvoLogger.logEventSent("Docs Page Errored", eventProperties, userProperties);
    if (__WEB_DEBUGGER__) {
      // Avo web debugger
      _avo_debugger_log("Pjs0MGxPME", "Docs Page Errored", messages, eventPropertiesArray, userPropertiesArray, []);
    }
  }
  if (!__AVO_NOOP__) {
    if (__INSPECTOR__ != null) {
      // @ts-ignore
      __INSPECTOR__._avoFunctionTrackSchemaFromEvent("Docs Page Errored", eventProperties, "Pjs0MGxPME", EVENT_HASH_Pjs0MGxPME_58210381);
    }
    // destination SegmentInspectorForDocs
    SegmentInspectorForDocs.logEvent("Docs Page Errored", (Object as any).assign({}, eventProperties), {});
    
    // destination Intercom
    let intercomProperties = {};
    Intercom.logEvent("Docs Page Errored", (Object as any).assign({}, intercomProperties));
    
    // destination Fullstory
    Fullstory.logEvent("Docs Page Errored", (Object as any).assign({}, eventProperties));
    
    // destination Mixpanel
    Mixpanel.logEvent("Docs Page Errored", (Object as any).assign({}, eventProperties));
  } else {
    // do nothing
  }
}

export default docsPageErrored;