// Generated by Avo. You should never have to make changes to this file.
// If you find yourself in the situation where you have to edit the file please contact us at hi@avo.app.
// If you encounter a git conflict in this file run `avo pull` and it will be resolved automatically.
/* tslint:disable */
/* eslint-disable */
// @ts-nocheck

// Event hashes for Inspector tracking
export const EVENT_HASH__2ec69c49_7376_4821_b584_8399845d33d7_32066347 = "006c3fdb9d103c893bc7c840055a4a24bbe97b8b83892ee41dccbdd4ab6c152c";
export const EVENT_HASH__0FvnJgpVbz_795a0069 = "a1957ef9b84b8f29012e1e9f97ff61250039ea456028ff892b1392f196baee65";
export const EVENT_HASH_J4cW6PmriY_42340bcd = "6d8c90f03c2974c66a50d66baf1960bbfee24f1d21df493811d0917fdecfaa22";
export const EVENT_HASH_Pjs0MGxPME_58210381 = "34e042e4d14cf388e917a678968cfa23b16173fcca2d6acffffd6fc76ae99c6a";