// Generated by Avo. You should never have to make changes to this file.
// If you find yourself in the situation where you have to edit the file please contact us at hi@avo.app.
// If you encounter a git conflict in this file run `avo pull` and it will be resolved automatically.
/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
import * as AvoRuntime from '../Avo';

import { EVENT_HASH__2ec69c49_7376_4821_b584_8399845d33d7_32066347 } from './EventHashes0';
import type { AvoAssertMessage } from '../Avo';

import type {
SiteSectionValueType
} from '../Avo';
export interface SignUpStartedProperties {
  siteSection: SiteSectionValueType;
  emailInput: string | null | undefined;
  path: string;
}
/**
 * Sign Up Started: Sent whenever users initiate the signup flow from the landing page. As this is written, that means: All the buttons with Try Avo for FREE.
 * 
 * @param properties the properties associated with this event
 * @param properties.siteSection: no description
 * @param properties.emailInput: The email address that is put into the email input on the landing page
 * @param properties.path: pathname from the URL, e.g. 'https://www.avo.app/docs/quickstart/' -> 'docs/quickstart'
 * 
 * @see {@link https://www.avo.app/schemas/fwtXqAc0fCLy7b7oGW40/events/2ec69c49-7376-4821-b584-8399845d33d7}
 */
export function signUpStarted(properties: SignUpStartedProperties) {
  
  // Get destinations from AvoRuntime
  const { 
    AvoEnv,
    __AVO_ENV__,
    __AVO_NOOP__,
    __AVO_LOGGER__,
    __STRICT__,
    __REPORT_FAILURE_AS__,
    InternalAvoLogger,
    array_difference,
    AvoAssert,
    _avo_invoke,
    _avo_invoke_meta,
    convertPropertiesArrayToMap,
    getSystemProperties,
    __WEB_DEBUGGER__,
    _avo_debugger_log,
    __INSPECTOR__,
    SegmentInspectorForDocs,
    Intercom,
    Fullstory,
    Mixpanel } = AvoRuntime;
  // Get system properties at runtime when the function is called
  const {
    sysClient,
    sysVersion
  } = getSystemProperties();
  
  // @ts-ignore
  let eventPropertiesArray: array = [];
  eventPropertiesArray.push({id: "0864af21-75be-467e-b281-6a43e52e770c", name: "Site Section", value: properties.siteSection});
  properties.emailInput !== undefined && properties.emailInput !== null ?
    eventPropertiesArray.push({id: "439349b2-72cb-4ac1-81d9-1c4aa89da524", name: "Email Input", value: properties.emailInput}) :
    eventPropertiesArray.push({id: "439349b2-72cb-4ac1-81d9-1c4aa89da524", name: "Email Input", value: null});
  eventPropertiesArray.push({id: "UT9ZlNsN2", name: "Path", value: properties.path});
  eventPropertiesArray.push({id: "9e5c4ff5-d5f6-4e82-b061-d5fa02755aae", name: "Client", value: sysClient});
  eventPropertiesArray.push({id: "2fad5bf3-7782-49a2-acc2-825daf823095", name: "Version", value: sysVersion});
  let eventProperties = convertPropertiesArrayToMap(eventPropertiesArray)
  // @ts-ignore
  let userPropertiesArray: array = [];
  let userProperties = convertPropertiesArrayToMap(userPropertiesArray)
  // assert properties
  if (__AVO_ENV__ !== AvoEnv.Prod || __WEB_DEBUGGER__) {
    let messages: AvoAssertMessage[] = [];
    // debug console in Avo
    if (!__AVO_NOOP__) {
      _avo_invoke(__AVO_ENV__, "2ec69c49-7376-4821-b584-8399845d33d7", EVENT_HASH__2ec69c49_7376_4821_b584_8399845d33d7_32066347, messages.map(m => Object.assign({}, {tag: m.tag, propertyId: m.propertyId, additionalProperties: m.additionalProperties, actualType: m.actualType})), 'event');
    }
    InternalAvoLogger.logEventSent("Sign Up Started", eventProperties, userProperties);
    if (__WEB_DEBUGGER__) {
      // Avo web debugger
      _avo_debugger_log("2ec69c49-7376-4821-b584-8399845d33d7", "Sign Up Started", messages, eventPropertiesArray, userPropertiesArray, []);
    }
  }
  if (!__AVO_NOOP__) {
    if (__INSPECTOR__ != null) {
      // @ts-ignore
      __INSPECTOR__._avoFunctionTrackSchemaFromEvent("Sign Up Started", eventProperties, "2ec69c49-7376-4821-b584-8399845d33d7", EVENT_HASH__2ec69c49_7376_4821_b584_8399845d33d7_32066347);
    }
    // destination SegmentInspectorForDocs
    SegmentInspectorForDocs.logEvent("Sign Up Started", (Object as any).assign({}, eventProperties), {});
    
    // destination Intercom
    let intercomProperties = {};
    Intercom.logEvent("Sign Up Started", (Object as any).assign({}, intercomProperties));
    
    // destination Fullstory
    Fullstory.logEvent("Sign Up Started", (Object as any).assign({}, eventProperties));
    
    // destination Mixpanel
    Mixpanel.logEvent("Sign Up Started", (Object as any).assign({}, eventProperties));
  } else {
    // do nothing
  }
}

export default signUpStarted;