// Generated by Avo. You should never have to make changes to this file.
// If you find yourself in the situation where you have to edit the file please contact us at hi@avo.app.
// If you encounter a git conflict in this file run `avo pull` and it will be resolved automatically.
/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
export interface AvoEventsModuleMap {
  signUpStarted: typeof import('./signUpStarted').default;
  branchPromptInteraction: typeof import('./branchPromptInteraction').default;
  contentCopied: typeof import('./contentCopied').default;
  docsPageViewed: typeof import('./docsPageViewed').default;
  docsPageErrored: typeof import('./docsPageErrored').default;
}
export type EventName = keyof AvoEventsModuleMap;
export type EventFn<T extends EventName = EventName> = AvoEventsModuleMap[T];

