name: Lint, spellcheck and avo status

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-linting-spelling-avo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install modules
        run: bun install
      - name: Check linting
        run: bun run lint
        env:
          CI: true
      - name: Check spelling
        run: bun run spellcheck
      - name: Check avo status
        run: bun run avo status
