name: Lint and Typecheck

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        #node-version: [8.x, 10.x, 12.x]
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn lint
        env:
          CI: true
      - run: yarn lint-mdx
        if: ${{ always() }}
        env:
          CI: true
          GITHUB_SECRET: ${{secrets.GITHUB_TOKEN}}
          OWNER: avohq
          REPO: docs
